### ISSUE TITLE
Integrate GTFS Static

### ISSUE THREAD

**Issue by bryanjhdang** [JoshuaJLi/cmpt362-wtb#1]
Use the TransLink Open API and to grab both GTFS Realtime and GTFS Static Data. Developers should be able to easily grab bus schedules according to a specific stop number.

GTFS ("General Transit Feed Specification") is a common format for public transportation schedules.

- https://www.translink.ca/about-us/doing-business-with-translink/app-developer-resources
- https://www.translink.ca/about-us/doing-business-with-translink/app-developer-resources/gtfs
- https://www.translink.ca/about-us/doing-business-with-translink/app-developer-resources/gtfs/gtfs-realtime
- https://www.translink.ca/about-us/doing-business-with-translink/app-developer-resources/gtfs/gtfs-data

**Comment by bryanjhdang** [comment]
Splitting this into 2 tasks as the scope is pretty big - one for static data and one for real-time.

**Comment by toastjpg** [comment]
Reference for GTFS file types: https://gtfs.org/documentation/schedule/reference/

Static data downloaded from translink needs to cleaned + transformed to match our data model.

Doing it here: https://github.com/toastjpg/gtfs-static-cleaning/tree/main

**Comment by toastjpg** [comment]
Blocked/no progress until there's a cleaner method to associate date/time to an bus arrival time. Bus schedules are not regular and differ on holidays. Some bus routes are also infrequent/special and run on certain days only.
