### ISSUE TITLE
Nearby screen shows nearby bus stops

### ISSUE THREAD

**Issue by JoshuaJLi** [JoshuaJLi/cmpt362-wtb#3]
We need a view that shows nearby bus stops on a Google Maps view.
- tapping on a marker should bring up stop information and suggest the user add it to favourites

**Comment by JoshuaJLi** [comment]
![Image](https://github.com/user-attachments/assets/c8795344-1d6b-4206-8a45-0e6e7c0e64cf)

**Comment by ethanchou128** [comment]
todo:
- "migrate" Stop class object into the actual BusStop object we want to use (Stop was from hackathon)
- clean it up because theres some junk code in there, and then do what josh said above re: grouping pings together
