### ISSUE TITLE
Settings Fragment

### ISSUE THREAD

**Issue by bryanjhdang** [JoshuaJLi/cmpt362-wtb#34]
Create the settings fragment. Some settings to include:
- theme
- configure search results (amount of results)
- nearby bus stop radius limit
- NFC on tap functionality (what it should do on tap)
- contact / support

This is a LOW PRIORITY task. If there's other stuff to do, don't do this.

**Comment by toastjpg** [comment]
https://github.com/JoshuaJLi/cmpt362-wtb/pull/40#discussion_r1864098195

limit search to max n results
