### ISSUE TITLE
Optimize location tracking and recentering

### ISSUE THREAD

**Issue by yenuGH** [JoshuaJLi/cmpt362-wtb#46]
# TODO

- Optimize the tracking of the user's current location
    - Make the intervals smaller?
    - Smoother animations?
- Make recentering faster
- Request location permissions on app startup instead of in the nearby fragment

**Comment by bryanjhdang** [comment]
Make it so that when clicking on a marker, the radius doesn't update too and render all the new markers around it. It can still center, just don't update the radius detection.
