### ISSUE TITLE
Integrate GTFS static schedules

### ISSUE THREAD

**Issue by bryanjhdang** [JoshuaJLi/cmpt362-wtb#49]
A lot of the time, realtime will just display "no upcoming buses". We want to supplement this with GTFS static schedule information.

**Comment by toastjpg** [comment]
The cleaned static stop_times json file is around 40 mb of data. After converting to realm objects and populating the database with all other static data, the total database file is around 100 mb. 

For stop_times, loading and inserting into database is around 40 seconds. 
Stop and routes informations much faster at around 3 seconds.

**Comment by toastjpg** [comment]
!!!!

https://www.mongodb.com/docs/atlas/device-sdks/sdk/kotlin/realm-database/realm-files/bundle-a-realm/#populate-an-asset-realm-with-seed-data
